---
sudo: required

services:
  - docker

# set language to anythoing other than Ruby so it doesn't use RVM which winds up overriding the RUBY_VERSION variable
language: c

env:
  - RUBY_VERSION=2.2.5
  - RUBY_VERSION=2.3.1

install: true

script: set -x; docker build --tag "quay.io/goodguide/ruby:ubuntu-15.10-${RUBY_VERSION}-${TRAVIS_BUILD_NUMBER}" --build-arg RUBY_VERSION="${RUBY_VERSION}" .
