#!/bin/bash

set -euo pipefail

tag_ruby_id="${RUBY_VERSION}"
if [[ $tag_ruby_id =~ ^[0-9] ]]; then
   tag_ruby_id="mri-${tag_ruby_id}"
fi

tag="quay.io/goodguide/ruby:${TAG_BASE}-${tag_ruby_id}-${TRAVIS_BUILD_NUMBER}"

docker build --file "${DOCKERFILE:-Dockerfile}" --tag "${tag}" --build-arg RUBY_VERSION="${RUBY_VERSION}" .

echo docker push "${tag}"
